# Generated by Django 4.0.9 on 2023-02-11 19:16

from django.db import migrations, models
import django.db.models.deletion
import votos.locations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='locations.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_stations', to='locations.municipality', verbose_name='Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(validators=[votos.locations.validators.validate_positive], verbose_name='Number')),
                ('votes', models.BigIntegerField(validators=[votos.locations.validators.validate_positive], verbose_name='Votes')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='locations.pollingstation', verbose_name='PollingStation')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
