# Generated by Django 4.0.9 on 2023-02-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_department_municipality_pollingstation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='pollingstation',
            unique_together={('name', 'municipality')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'polling_station')},
        ),
    ]
