# Generated by Django 4.0.9 on 2023-02-12 01:45

from django.db import migrations, models
import votos.locations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='votes',
            field=models.BigIntegerField(default=0, validators=[votos.locations.validators.validate_positive], verbose_name='Votes'),
        ),
    ]
