# Generated by Django 4.0.9 on 2023-02-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_department_municipality_pollingstation_table_and_more'),
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Names')),
                ('surnames', models.CharField(max_length=255, verbose_name='Surnames')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User name')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('cc', models.CharField(max_length=255, verbose_name='Citizenship card')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Names')),
                ('surnames', models.CharField(max_length=255, verbose_name='Surnames')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User name')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('cc', models.CharField(max_length=255, verbose_name='Citizenship card')),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to='voters.administrator', verbose_name='Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Names')),
                ('surnames', models.CharField(max_length=255, verbose_name='Surnames')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User name')),
                ('cc', models.CharField(max_length=255, verbose_name='Citizenship card')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('neighborhood', models.CharField(blank=True, max_length=255, verbose_name='Neighborhood')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='voters.leader', verbose_name='Leader')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='locations.table', verbose_name='Table')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
