# Generated by Django 4.0.9 on 2023-02-12 00:01

from django.db import migrations, models
import votos.voters.validators


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_rename_created_at_voter_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='cc',
            field=models.CharField(max_length=255, validators=[votos.voters.validators.validate_string_number], verbose_name='Citizenship card'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='cc',
            field=models.CharField(max_length=255, validators=[votos.voters.validators.validate_string_number], verbose_name='Citizenship card'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='cc',
            field=models.CharField(max_length=255, validators=[votos.voters.validators.validate_string_number], verbose_name='Citizenship card'),
        ),
    ]
